"""fixed testimonial in PresPost

Revision ID: 1b432b2e5088
Revises: 855fc6619625
Create Date: 2022-11-05 19:37:41.589820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b432b2e5088'
down_revision = '855fc6619625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pres_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testimonial1', sa.Text(), nullable=True))
        batch_op.drop_column('testimonial')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pres_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testimonial', sa.TEXT(), nullable=True))
        batch_op.drop_column('testimonial1')

    # ### end Alembic commands ###
