"""+ campi Wpost

Revision ID: 674daa8d6d4c
Revises: 8eb0316f139e
Create Date: 2022-11-20 21:49:14.805358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674daa8d6d4c'
down_revision = '8eb0316f139e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wpost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('body4', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('body5', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('testimonial1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('testimonial2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('testimonial3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=120), nullable=True))
        batch_op.drop_column('testimonial')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wpost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testimonial', sa.TEXT(), nullable=True))
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('testimonial3')
        batch_op.drop_column('testimonial2')
        batch_op.drop_column('testimonial1')
        batch_op.drop_column('body5')
        batch_op.drop_column('body4')
        batch_op.drop_column('body3')

    # ### end Alembic commands ###
