"""Aggiunta immagine user

Revision ID: 855fc6619625
Revises: 7c70bde2bcc0
Create Date: 2022-11-04 22:54:32.281439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855fc6619625'
down_revision = '7c70bde2bcc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
