"""Nuovi campi in PresPost

Revision ID: 8eb0316f139e
Revises: 1b432b2e5088
Create Date: 2022-11-17 15:26:56.412887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb0316f139e'
down_revision = '1b432b2e5088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pres_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body5', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('testimonial3', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pres_post', schema=None) as batch_op:
        batch_op.drop_column('testimonial3')
        batch_op.drop_column('body5')

    # ### end Alembic commands ###
