"""Un solo body

Revision ID: ad0d51f3b1db
Revises: 8a4fd089fdbd
Create Date: 2022-10-18 22:50:49.484326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0d51f3b1db'
down_revision = '8a4fd089fdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.drop_column('body1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body1', sa.TEXT(), nullable=False))
        batch_op.drop_column('body')

    # ### end Alembic commands ###
