"""Image modificato con cover

Revision ID: ae35948c8765
Revises: d1ae47ad1137
Create Date: 2022-10-22 23:47:17.977390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae35948c8765'
down_revision = 'd1ae47ad1137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=120), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
